name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan 34.118.123.198 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh prani@34.118.123.198 "
          cd /home/prani/devops-project &&
          git pull origin main &&
          sudo systemctl restart app
        "
